# Copyright 2020 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name: CI
on: [push]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
      fail-fast: false

    steps:
    - run: systeminfo
    - run: git config --global core.autocrlf false
    - run: git config --global core.eol lf
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.13.0'
    - run: npm install -g yarn@1.22.0

    - run: set npm_config_arch=${{ matrix.arch }}
      shell: cmd
    - run: yarn install --frozen-lockfile
    - run: yarn generate
    - run: yarn lint
    - run: node build\grunt.js
    - run: yarn test-node
    - run: copy package.json temp.json
    - run: del package.json
    - run: type temp.json | findstr /v certificateSubjectName | findstr /v certificateSha1 > package.json
    - run: yarn prepare-beta-build
    - run: yarn build
    - run: node build\grunt.js test
    - run: node build\grunt.js test-release:win
      env:
        SIGNAL_ENV: production
