# Copyright 2020 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name: CI
on: [push]

jobs:
  windows:
    runs-on: windows-latest
    env:
      npm_config_arch: ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [x64, arm64]
      fail-fast: false

    steps:
    - run: systeminfo
    - run: git config --global core.autocrlf false
    - run: git config --global core.eol lf
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.15.0'
    - run: npm install -g yarn
    - run: npm install -g node-gyp@5.1.0

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.arch }}-node_modules-${{ hashFiles('package.json') }}

    - run: curl -s -O C:\\Users\\runneradmin\\AppData\\Local\\node-gyp\\Cache\\12.15.0\\arm64\\node.lib https://unofficial-builds.nodejs.org/download/release/v12.15.0/win-arm64/node.lib
    - run: yarn install
    - run: yarn generate
    - run: yarn lint
    - run: node build\grunt.js
    - run: yarn test-node
    - run: copy package.json temp.json
    - run: del package.json
    - run: type temp.json | findstr /v certificateSubjectName | findstr /v certificateSha1 > package.json
    - run: yarn prepare-beta-build
    - run: yarn build
    - run: node build\grunt.js test
    - run: node build\grunt.js test-release:win
      env:
        SIGNAL_ENV: production
